config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  get  '/auth/:provider/callback', to: 'users#google_login', as:'google_login'
  root 'tops#top'
  get 'battle' => 'battle#index'

  resources :users, only: [:create]
  resources :rooms, only: [:show, :create, :index, :destroy] do
    get :input_password, on: :member, as:'input_password'
    post :authenticate, on: :member, as:'authenticate'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content, presence: true, length: { maximum: 150 }
    # createの後にコミットする { MessageBroadcastJobのperformを遅延実行 引数はself }
    after_create_commit { MessageBroadcastJob.perform_later self }
    belongs_to :user, required: true
    belongs_to :room, required: true
    mount_uploader :image, ImagesUploader
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
    has_and_belongs_to_many :users
    has_secure_password validations: false
    validate(on: :update) do |record|
        record.errors.add(:password, :blank) unless record.password_digest.present?
    end
    validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED, on: :update
    validates_confirmation_of :password, allow_blank: true, on: :update
    validates :name, presence: true, length: { maximum: 30 }
    validates :description, presence: true, length: { maximum: 60 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    #DB保存前に小文字に変換

    validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
    validates :email, presence: true,
    uniqueness: { case_sensitive: false },
    #大文字・小文字の区別なし
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    #「/i」は大文字・小文字を区別せずにマッチングさせる正規表現
    has_many :messages
    has_and_belongs_to_many :rooms
    has_secure_password validations: false
    validates :password, length: (6..32), presence: true, confirmation: true, unless: :google_user?

    private
    def google_user?
        self.uid.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
    def index
        @card_list = Card.order(id: "ASC").where(opend: false).group(:name).count
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @rooms = Room.all.order(created_at: :desc)
    @rooms = Room.page(params[:page]).per(15)
    @room = Room.new
  end

  def show
    @room = Room.find(params[:id])
    if @room.password_digest.present? && session[:authenticated_room] != @room.id
      redirect_to rooms_path
    else
      current_user.rooms << @room
      current_user.save
      @users = User.includes(:rooms).where('rooms.id' => @room.id)
      @messages = @room.messages.last(50)
      session.delete(:authenticated_room)
    end
  end

  def create
    room = Room.new(room_params)
    room.save
    session[:authenticated_room] = room.id
    redirect_to room_path(room.id)
  end

  def input_password
    @room = Room.find(params[:id])
  end

  def authenticate
    room = Room.find(params[:id])
    if room.authenticate(params[:room][:password])
      session[:authenticated_room] = room.id
      redirect_to room_path(room)
    else
      @room = room
      render :input_password
    end
  end

  private
  def room_params
    params.require(:room).permit(:name, :description, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to root_path
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def top
        @room = Room.new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to rooms_path
        else
            render action: "new"
        end
    end

    def google_login
        user = User.find_or_create_by(uid: request.env['omniauth.auth']['uid'] )
        if user.name.blank?
            user.name = request.env['omniauth.auth']['info']['name']
            user.email = request.env['omniauth.auth']['info']['email']
            user.uid = request.env['omniauth.auth']['uid']
            user.save
        end
        log_in(user)
        redirect_to rooms_path
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :last_sending_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def authenticate_user!
        if current_user.nil?
            redirect_to root_path
        end
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/battle/index.html.erb
<% @card_list.each do |name, left_cards| %>
    <%= name %><%= left_cards%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tadano-Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav class="header">
      <div class="nav-wrapper">
        <div class="container">
          <a href="/" class="brand-logo">Tadano-Chat</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if logged_in? %>
              <li><%= current_user.name + "さん" %></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to '新規登録', signup_path %></li>
              <li><%= link_to 'ログイン', login_path %></li>
            <% end %>
            <li><a href="https://github.com/Tom0430/chat-practice">Git Hub</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class='message'>
    <% if message.image.present? %>
        <%= message.image %>
    <% end %>
    <p><%= "#{message.created_at.to_s(:time)} #{message.user.name}: #{message.content}" %></p>
</div>

app/views/rooms/index.html.erb
<div class="container">
    <div class="new-room">
        <h5>チャットルーム新規作成</h5>
        <%= form_for( @room , remote: true, url: rooms_path, method: "post" ) do |f| %>
            <%= f.label :"ルームの名前を決めてください" %>
            <%= f.text_field :name %>
            <%= f.label :"メンバーを募集するためのメッセージを書きましょう" %>
            <%= f.text_field :description %>
            <%= f.label :"パスワードを設定したい方はこちらに入力してください" %>
            <%= f.password_field :password %>
            <div class="btn"><%= f.submit "new room", class: "room-submit"%></div>
        <% end %>
    </div>

    <%= link_to "LoveLetterをプレイする", battle_path %>
    <% @rooms.each do |room| %>
        <div class="card-panel hoverable">
            <div class="card-image"></div>
            <div class="card-content">
                <% if room.password_digest.present? %>
                    <i class="small material-icons">lock_outline</i>
                    <%= link_to "「#{room.name}」", input_password_room_path(room) %>
                <% else %>
                    <%= link_to "「#{room.name}」", room_path(room) %>
                <% end %>
            </div>
            <div class="card-action"><%= room.description %></div>
        </div>
    <% end %>
<%= paginate @rooms %>
</div>

app/views/rooms/input_password.html.erb
<%= @room.name %>
<p>このルームはパスワードの入力が必要です。</p>
<%= form_for(:room, url: authenticate_room_path) do |f| %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "送信", class: "btn btn-primary" %>
<% end %>

app/views/rooms/show.html.erb
<div class="chat-room">
    <h5><%= @room.name %></h5>
    <div id='messages'data-room_id="<%= @room.id %>" class="chat-texts" >
        <%= render @messages %>
    </div>

    <div class="chat-form">
        <%= label_tag :content, 'ここに文章を入力してください', class: "text-label" %>
        <%= text_field_tag :content, nil, data: { behavior: 'room_speaker' }, class: "chat-text-field" %>
        <span class="room-name"><%= "「"+ @room.name + "」" %></span>
        <%= link_to "ルーム一覧へ", rooms_path, class: "rooms-link" %>
        <span>送信した文章が表示されない場合はリロードしてください</span>
    </div>
</div>

<script>
$(document).ready( function(){
if (window.name != "test") {
location.reload();
window.name = "test";
} else {
window.name = "";
}
});
</script>

app/views/tops/top.html.erb
<div class="container">
    <h3>ようこそTadano-Chatへ！</h3>
    <p>絵文字も写真も送れないですが、無料のチャットサイトです。</p>
    <% if logged_in? %>
        <p>下の一覧から入りたいチャットルームを選んで楽しくチャットしてください！</p>
        <p>パスワードを設定することもできます。</p>
        <%= link_to  "チャットルーム一覧", rooms_path %>
    <% else %>
        <p>まずは新規登録、またはログインをお願いします</p>
        <p><%= link_to  "新規登録", signup_path %></p>
        <p><%= link_to  "ログイン", login_path %></p>
        <p><%= link_to 'グーグルアカウントでログイン', "/auth/google_oauth2", id: "sign_in" %></p>
    <% end %>
</div>

app/views/users/new.html.erb
<h5>ユーザー登録</h5>
<%= form_for @user do |f| %>
<%# render 'layouts/error_messages', model: f.object %>

<div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>
<%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>